name: learnit
version: "0.2"
summary: Learn through flashcards
description: Learn through flashcards from external card files
confinement: strict

apps:
  run:
    command: bin/learnit

parts:
  learnit:
    plugin: go
    source: https://github.com/knitzsche/flashcards
    go-importpath: github.com/knitzsche/flashcards
    source-type: git      
    snap:
      - bin/flashcards
  cards:
    plugin: copy
    files:
      nato_alph.txt: nato_alph.txt
      learnit.wrapper: bin/learnit

