name: learnit
version: "0.4"
summary: Learn through flashcards
description: Learn through flashcards from external card files
confinement: strict

apps:
  run:
    command: bin/learnit

parts:
  flashcards:
    plugin: go
    source: https://github.com/knitzsche/flashcards
    go-importpath: github.com/knitzsche/flashcards
    source-type: git      
    snap:
      - bin/flashcards

  learnit:
    plugin: dump 
    source: https://github.com/knitzsche/learnit
    source-type: git      
    organize:
      learnit.wrapper: bin/learnit

  cards:
    plugin: dump
    source: data
