name: learnit
version: "1"
summary: Learn through flashcards
description: Learn through flashcards from external card files
base: core20
confinement: strict
grade: stable

apps:
  learnit:
    command: bin/learnit.sh
    plugs: [ home ]

parts:
  flashcards:
    plugin: go
    source: https://github.com/knitzsche/flashcards
    source-type: git      

  learnit:
    plugin: dump 
    source: https://github.com/knitzsche/learnit
    source-type: git      
    organize:
      learnit.wrapper: bin/learnit

  launchers:
    source: launchers
    plugin: dump

  cards:
    plugin: dump
    source: data
